import { pgTable, text, timestamp, boolean, jsonb, integer } from 'drizzle-orm/pg-core';

export const masterSongs = pgTable('master_songs', {
  id: text('id').primaryKey(),
  title: text('title'),
  key: text('key'),
  tempo: text('tempo'),
  lyrics: text('lyrics'),
  writer: text('writer'),
  solfa: text('solfa'),
  category: text('category'),
  imageUrl: text('image_url'),
  audioFile: text('audio_file'),
  audioUrls: jsonb('audio_urls'),
  conductor: text('conductor'),
  leadSinger: text('lead_singer'),
  drummer: text('drummer'),
  bassGuitarist: text('bass_guitarist'),
  leadKeyboardist: text('lead_keyboardist'),
  categories: jsonb('categories'),
  customParts: jsonb('custom_parts'),
  publishedAt: timestamp('published_at'),
  publishedBy: text('published_by'),
  publishedByName: text('published_by_name'),
  updatedAt: timestamp('updated_at'),
  sourceType: text('source_type'),
  isHqOnly: boolean('is_hq_only'),
});

export const praiseNightSongs = pgTable('praise_night_songs', {
  id: text('id').primaryKey(),
  title: text('title'),
  key: text('key'),
  tempo: text('tempo'),
  lyrics: text('lyrics'),
  writer: text('writer'),
  category: text('category'),
  audioFile: text('audio_file'),
  audioUrls: jsonb('audio_urls'),
  conductor: text('conductor'),
  leadSinger: text('lead_singer'),
  drummer: text('drummer'),
  zoneId: text('zone_id'),
  praiseNightId: text('praise_night_id'),
  status: text('status'),
  isActive: boolean('is_active'),
  categories: jsonb('categories'),
  createdAt: text('created_at'),
  updatedAt: timestamp('updated_at'),
});
